FROM node:18 as build

WORKDIR /frontend
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm install
COPY ./frontend/ ./
RUN npm run build


FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.prod.conf /etc/nginx/conf.d
COPY --from=build /frontend/build /usr/share/nginx/html
